In [96]:
import pandas as pd
df = pd.read_csv('./full_dataset.csv')

In [97]:
df

Duration  FlowBytesSent  FlowSentRate  FlowBytesReceived  \
0       95.081550          62311    655.342703              65358   
1      122.309318          93828    767.136973             101232   
2      120.958413          38784    320.639127              38236   
3      110.501080          61993    561.017141              69757   
4       54.229891          83641   1542.341289              76804   
...           ...            ...           ...                ...   
39609  120.489229          24155    200.474351              39526   
39610  120.522576          51632    428.401066              32080   
39611  120.360950          47923    398.160699              88167   
39612  120.608554          44979    372.933747              86529   
39613  120.642706          45883    380.321376              89641   

       FlowReceivedRate  PacketLengthVariance  PacketLengthStandardDeviation  \
0            687.388878           7474.676771                      86.456213   
1            827.672018          10458.118600                     102.264943   
2            316.108645           7300.293933                      85.441758   
3            631.278898           8499.282518                      92.191553   
4           1416.266907           8052.745751                      89.737092   
...                 ...                   ...                            ...   
39609        328.045920          40999.197040                     202.482585   
39610        266.174198          24846.903090                     157.629005   
39611        732.521636          33856.106820                     184.000290   
39612        717.436675          33823.060610                     183.910469   
39613        743.028758          33324.590930                     182.550242   

       PacketLengthMean  PacketLengthMedian  PacketLengthMode  ...  \
0            135.673751               102.0                54  ...   
1            141.245474               114.0                54  ...   
2            133.715278                89.0                54  ...   
3            139.123548               114.0                54  ...   
4            138.913420               114.0               114  ...   
...                 ...                 ...               ...  ...   
39609        168.915119               148.0                68  ...   
39610        195.132867               180.0                68  ...   
39611        243.017857               257.0                68  ...   
39612        250.015209               257.0                68  ...   
39613        258.633588               257.0                68  ...   

       PacketTimeCoefficientofVariation  ResponseTimeTimeVariance  \
0                              0.574626                  0.001053   
1                              0.509047                  0.001170   
2                              0.732636                  0.000785   
3                              0.646859                  0.000411   
4                              0.507334                  0.079079   
...                                 ...                       ...   
39609                          0.675699                  0.104322   
39610                          0.514797                  0.179608   
39611                          0.569166                  0.027457   
39612                          0.576832                  0.032776   
39613                          0.595560                  0.015896   

       ResponseTimeTimeStandardDeviation  ResponseTimeTimeMean  \
0                               0.032457              0.027624   
1                               0.034200              0.024387   
2                               0.028021              0.029238   
3                               0.020274              0.019925   
4                               0.281209              0.025930   
...                                  ...                   ...   
39609                           0.322989              0.184579   
39610                

In [98]:
X = df.drop(['ResponseTimeTimeMedian','ResponseTimeTimeSkewFromMedian','Label'], axis=1)
y = df['Label']

Dataset split

In [99]:
from sklearn.preprocessing import StandardScaler

std = StandardScaler()

In [100]:
std.fit(X)

# 학습 데이터 스케일링
X_scaled = std.transform(X)
X = X_scaled

In [101]:
X

array([[ 0.91082026,  0.07800172, -0.1105849 , ..., -0.11113174,
         0.02988006,  0.00529606],
       [ 1.4318847 ,  0.26557253, -0.11031832, ..., -0.11104515,
        -0.00160916,  0.12070614],
       [ 1.4060321 , -0.06201726, -0.11138301, ..., -0.11111377,
         0.04877682, -0.10461618],
       ...,
       [ 1.39459831, -0.00762726, -0.11119816, ..., -0.11136047,
         0.14513459,  0.32817074],
       [ 1.39933677, -0.02514824, -0.11125831, ..., -0.11133869,
         0.13374734,  0.41897873],
       [ 1.39999034, -0.01976815, -0.1112407 , ..., -0.11135612,
         0.11281607,  0.42591892]])

In [102]:
X.shape

(39614, 27)

## PCA

In [103]:
from sklearn import decomposition
Pca = decomposition.PCA(n_components=5)
x_pca = Pca.fit_transform(X)

In [104]:
x_pca

array([[ 1.69881738,  0.51684734,  0.80077375,  0.58749067, -0.23572231],
       [ 2.17290306,  1.47876426,  1.16874919,  0.31257492,  0.38623364],
       [ 1.93395013,  1.16259043,  0.21601903,  0.14672269,  0.41211102],
       ...,
       [ 2.9625738 ,  2.27693639,  1.06955091, -0.3510349 , -0.22238196],
       [ 2.86719133,  2.3039465 ,  1.08981943, -0.32662893, -0.20168974],
       [ 2.65620987,  2.27852433,  1.141914  , -0.34405151, -0.18795266]])

In [105]:
x_pca.shape

(39614, 5)

In [106]:
pca = decomposition.PCA(n_components=27)
XX_pca = pca.fit_transform(X)

In [107]:
XX_pca[0]

array([ 1.69881735e+00,  5.16847240e-01,  8.00769238e-01,  5.87486315e-01,
       -2.35719831e-01, -4.81492745e-01, -8.24822558e-01, -9.35592809e-01,
       -4.15753123e-01, -6.44604180e-02, -3.48547205e-01,  2.49159346e-01,
       -9.59661736e-01, -7.68784306e-02, -1.99873074e-01,  7.12359143e-02,
       -4.50623918e-02, -5.80973674e-02,  2.12789138e-01,  2.11878095e-01,
       -1.23288183e-01,  5.12619350e-04,  2.56607641e-02, -5.84236721e-02,
       -6.68083505e-02, -5.22876776e-03,  3.37145504e-02])

In [108]:
x_pca

array([[ 1.69881738,  0.51684734,  0.80077375,  0.58749067, -0.23572231],
       [ 2.17290306,  1.47876426,  1.16874919,  0.31257492,  0.38623364],
       [ 1.93395013,  1.16259043,  0.21601903,  0.14672269,  0.41211102],
       ...,
       [ 2.9625738 ,  2.27693639,  1.06955091, -0.3510349 , -0.22238196],
       [ 2.86719133,  2.3039465 ,  1.08981943, -0.32662893, -0.20168974],
       [ 2.65620987,  2.27852433,  1.141914  , -0.34405151, -0.18795266]])

In [109]:
print(Pca.explained_variance_ratio_)

[0.24602239 0.13971111 0.10230665 0.08615068 0.07283588]


## new set

In [122]:
new = df[['Duration','FlowBytesSent','FlowSentRate','FlowBytesReceived','FlowReceivedRate','Label']]

In [123]:
new

Duration  FlowBytesSent  FlowSentRate  FlowBytesReceived  \
0       95.081550          62311    655.342703              65358   
1      122.309318          93828    767.136973             101232   
2      120.958413          38784    320.639127              38236   
3      110.501080          61993    561.017141              69757   
4       54.229891          83641   1542.341289              76804   
...           ...            ...           ...                ...   
39609  120.489229          24155    200.474351              39526   
39610  120.522576          51632    428.401066              32080   
39611  120.360950          47923    398.160699              88167   
39612  120.608554          44979    372.933747              86529   
39613  120.642706          45883    380.321376              89641   

       FlowReceivedRate  Label  
0            687.388878      0  
1            827.672018      0  
2            316.108645      0  
3            631.278898      0  
4           1416.266907      0  
...                 ...    ...  
39609        328.045920      1  
39610        266.174198      1  
39611        732.521636      1  
39612        717.436675      1  
39613        743.028758      1  

[39614 rows x 6 columns]

In [124]:
X = new.drop(['Label'],axis=1)
y = new['Label']

In [139]:
X

array([[ 0.91082026,  0.07800172, -0.1105849 ,  0.08543363, -0.12146393],
       [ 1.4318847 ,  0.26557253, -0.11031832,  0.30044456, -0.12091597],
       [ 1.4060321 , -0.06201726, -0.11138301, -0.07712216, -0.12291418],
       ...,
       [ 1.39459831, -0.00762726, -0.11119816,  0.22213945, -0.12128763],
       [ 1.39933677, -0.02514824, -0.11125831,  0.21232209, -0.12134656],
       [ 1.39999034, -0.01976815, -0.1112407 ,  0.23097387, -0.12124659]])

In [125]:
from sklearn.preprocessing import StandardScaler

std = StandardScaler()

In [126]:
std.fit(X)

# 학습 데이터 스케일링
X_scaled = std.transform(X)
X = X_scaled

In [133]:
#train:validation:test = 6:2:2

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.2, random_state=1)

In [134]:
X_train

array([[-0.90694852, -0.27788706, -0.0495093 , -0.29374534, -0.03865664],
       [-0.90666701, -0.28669516, -0.08984476, -0.28450336,  0.00453434],
       [ 1.42762674, -0.21161803, -0.11188104, -0.16745623, -0.12340781],
       ...,
       [-0.90848026, -0.29181933, -0.0859892 , -0.30566042, -0.09783767],
       [-0.65165854, -0.19281751, -0.10916487, -0.14214567, -0.11618677],
       [ 1.39535832,  0.76080184, -0.1086413 ,  1.45322295, -0.1146248 ]])

In [135]:
y_val

11379    0
38411    1
21524    1
29942    1
4655     0
        ..
12696    0
20986    1
37963    1
1873     0
9421     0
Name: Label, Length: 6339, dtype: int64

pilot Logistic Regression

In [113]:
from sklearn import datasets
import numpy as np
import pandas as pd
import sklearn
from sklearn.linear_model import LogisticRegression

In [136]:
#모델 만들기
model = LogisticRegression(class_weight='balanced')

param_grid = {'C': [1, 10, 100, 1000]}
clf = sklearn.model_selection.GridSearchCV(model, param_grid)

# 모델 학습
model = model.fit(X_train, y_train)

In [137]:
# 학습시킨 모델에 test
predictions = model.predict(X_test)

In [138]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

print("accuracy: ", accuracy_score(y_test, predictions))
print("recall: ", recall_score(y_test, predictions, zero_division=1))
print("precision: ", precision_score(y_test, predictions, zero_division=1))
print("f1 score: " ,f1_score(y_test, predictions,  average='weighted'))

accuracy:  0.6096175691026127
recall:  0.44283903675538655
precision:  0.6612414837244511
f1 score:  0.5984748959802888
